swarm:
  datasources:
    jdbc-drivers:
      org.postgresql:
        driver-class-name: org.postgresql.Driver
        xa-datasource-class-name: org.postgresql.xa.PGXADataSource
        driver-module-name: org.postgresql  
    data-sources:
      InventoryDS:
        driver-name: org.postgresql
        connection-url: jdbc:postgresql://172.28.129.1:5432/coolstore-uat
        user-name: coolstore-uat
        password: P@ssw0rdUAT
